### ISSUE TITLE
app-mesh GA and us-west-2 region limitation  ?

### ISSUE THREAD

**Issue by fmedery** [aws-samples/voteapp#79]
With App-mesh being GA and available in more than 10 regions now, is the us-west-2 limitation in the script still needed ?

**Comment by nithu0115** [comment]
@fmedery - Assuming you are talking about sanity check function[https://github.com/aws-samples/voteapp/blob/master/config/appmesh/deploy-mesh.sh#L55], it is no longer required as Appmesh is now generally available in multiple regions.

**Comment by fmedery** [comment]
It was indeed in the sanity check. Tx
