### ISSUE TITLE
syntax of AppMesh has changed causing script deployment errors

### ISSUE THREAD

**Issue by nbrandaleone** [aws-samples/voteapp#81]
The deployment scripts in 
  - voteapp/config/appmesh/config/virtualnodes
  - voteapp/config/appmesh/config/virtualrouters
no longer work, due to changes in the AppMesh API.

**Comment by kayaman** [comment]
same issue here @nbrandaleone

**Comment by angadisachin2** [comment]
I am also facing the issue.
There are no virtualservices under "voteapp/config/appmesh/config/"

**Comment by brentley** [comment]
Should be fixed now.
